- name: Get list of changed packages
  ansible.builtin.command: git diff --name-only HEAD~1 '*.yaml' ':!.zuul.yaml'
  register: build_melange_packages_file_list
  args:
    chdir: "{{ zuul_work_dir }}"

- name: Build package
  include_role:
    name: build-melange-package
  loop: "{{ build_melange_packages_file_list.stdout_lines }}"
  loop_control:
    loop_var: build_melange_package_file_name
  vars:
    build_melange_package_name: "{{ build_melange_package_file_name.split('.') | first }}"
