- hosts: localhost
  tasks:
    - name: Add repository server to hosts
      ansible.builtin.add_host:
        name: static-server
        ansible_host: "{{ promote_melange_packages_static_server_host }}"
        ansible_user: "{{ promote_melange_packages_static_server_user | default('ubuntu') }}"

- hosts: static-server
  roles:
    - ensure-melange
