- job:
    name: zuul-jobs-test-ensure-depot
    run: playbooks/test-ensure-depot/run.yaml

- project:
    check:
      jobs:
        - zuul-jobs-test-ensure-depot
    gate:
      jobs:
        - zuul-jobs-test-ensure-depot
